persist_directory: data/chroma_db
collection_name: agent_test_01
k: 5
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: [".txt", ".pdf"]

chunk_size: 200
chunk_overlap: 20
# 说实话，感觉这里分割的太细碎了，容易造成语义缺失，后续可以删除一下
separators: ["\n\n", "\n", ",", ".", "?", "!", "。", "，", "？", "！"]
